# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiple_channel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

from channel_signal_name import Ui_signalNames

from data_processing import getChannelData,getSubUnits,runChInformation

import numpy as np 
import time
import pandas as pd
import os

class Ui_project(object):
    selected_channel = np.array([]) #selected channel in the end 
    buffer = np.array([]) #buffer to store the clicked channels 
    button_mode = np.zeros(180,dtype=bool)
    signal_names = []
    
    ip_address = ""
    
    frequency = 1 
    
    measurement_name =""
    org = ""
    bucket = ""
    token = ""
    
    database_settings = []
    project_settings = []
    
    def openSignalNamesWindow(self,selected_channel):
        self.window = QtWidgets.QMainWindow()
        #print(selected_channel)
        self.ui_si = Ui_signalNames(selected_channel)
        self.ui_si.setupUi(self.window)
        #print("here")
        self.window.show()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 599)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.enterProjectName()
        
        self.multipleChannel()
        
        self.enterFrequency()
        
        self.enterIPAddress()
        
        self.enterDatabase()
        
        self.init = QtWidgets.QPushButton(self.centralwidget)
        self.init.setGeometry(QtCore.QRect(1105,155,50,50))
        self.init.setIcon(QtGui.QIcon('png/initialise.PNG'))
        self.init.setIconSize(QtCore.QSize(45,45))
        self.init.setObjectName("init")
        self.init.clicked.connect(self.initProject)
        
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(1105, 255, 50, 50))
        #self.save.setText("SAVE")
        self.save.setIcon(QtGui.QIcon('png/save.png'))
        self.save.setIconSize(QtCore.QSize(45,45))
        self.save.setObjectName("save")
        self.save.clicked.connect(self.saveProject)
        
        self.openFile = QtWidgets.QPushButton(self.centralwidget)
        self.openFile.setGeometry(QtCore.QRect(1105,355,50,50))
        self.openFile.setIcon(QtGui.QIcon('png/open.png'))
        self.openFile.setIconSize(QtCore.QSize(45,45))
        #self.openFile.setText("OPEN")
        self.openFile.setObjectName("openFile")
        self.openFile.clicked.connect(self.openProject)
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def enterProjectName(self):
        self.project_name = QtWidgets.QLabel(self.centralwidget)
        self.project_name.setGeometry(QtCore.QRect(855,29,80,16))
        self.project_name.setObjectName("project_name")
        self.project_name.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        #self.project_name.setStyleSheet("color:rgb(0,0,127)")
        
        self.project_name_e = QtWidgets.QLineEdit(self.centralwidget)
        self.project_name_e.setGeometry(QtCore.QRect(820, 58, 140, 20))
        self.project_name_e.setObjectName("project_name_e")
        self.project_name_e.setText("t")
        self.project_name_e.setAlignment(QtCore.Qt.AlignCenter)
        self.project_name_e.setStyleSheet( "border-width: 1px; border-style: solid; border-color: white white rgb(0,0,0) white;color:rgb(0,0,0)" );
    def multipleChannel(self):
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 210, 271, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(60, 390, 271, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(410, 30, 271, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(410, 210, 271, 151))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(410, 390, 271, 151))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(60, 30, 271, 151))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, -60, 21, 691))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.su1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.su1.setObjectName("su1")
        self.verticalLayout.addWidget(self.su1)
        self.su2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.su2.setObjectName("su2")
        self.verticalLayout.addWidget(self.su2)
        self.su3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.su3.setObjectName("su3")
        self.verticalLayout.addWidget(self.su3)
        
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(360, -60, 21, 691))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.su4 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.su4.setObjectName("su4")
        self.verticalLayout_3.addWidget(self.su4)
        self.su5 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.su5.setObjectName("su5")
        self.verticalLayout_3.addWidget(self.su5)
        self.su0 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.su0.setObjectName("su0")
        self.verticalLayout_3.addWidget(self.su0)
        
        
        self.ch101 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch101.setObjectName("ch101")
        self.gridLayout.addWidget(self.ch101, 0, 0, 1, 1)
        
        self.ch102 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch102.setObjectName("ch102")
        self.gridLayout.addWidget(self.ch102, 0, 1, 1, 1)
        
        self.ch103 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch103.setObjectName("ch103")
        self.gridLayout.addWidget(self.ch103, 0, 3, 1, 1)
        
        self.ch104 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch104.setObjectName("ch104")
        self.gridLayout.addWidget(self.ch104, 0, 4, 1, 1)
        
        self.ch105 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch105.setObjectName("ch105")
        self.gridLayout.addWidget(self.ch105, 0, 5, 1, 1)
        
        self.ch106 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch106.setObjectName("ch106")
        self.gridLayout.addWidget(self.ch106, 1, 0, 1, 1)
        
        self.ch107 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch107.setObjectName("ch107")
        self.gridLayout.addWidget(self.ch107, 1, 1, 1, 1)
        
        self.ch108 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch108.setObjectName("ch108")
        self.gridLayout.addWidget(self.ch108, 1, 3, 1, 1)
        
        self.ch109 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch109.setObjectName("ch109")
        self.gridLayout.addWidget(self.ch109, 1, 4, 1, 1)
        
        self.ch110 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch110.setObjectName("ch110")
        self.gridLayout.addWidget(self.ch110, 1, 5, 1, 1)
        
        self.ch111 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch111.setObjectName("ch111")
        self.gridLayout.addWidget(self.ch111, 2, 0, 1, 1)
        
        self.ch112 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch112.setObjectName("ch112")
        self.gridLayout.addWidget(self.ch112, 2, 1, 1, 1)
        
        self.ch113 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch113.setObjectName("ch113")
        self.gridLayout.addWidget(self.ch113, 2, 3, 1, 1)
        
        self.ch114 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch114.setObjectName("ch114")
        self.gridLayout.addWidget(self.ch114, 2, 4, 1, 1)
        
        self.ch115 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch115.setObjectName("ch115")
        self.gridLayout.addWidget(self.ch115, 2, 5, 1, 1)
        
        self.ch116 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch116.setObjectName("ch116")
        self.gridLayout.addWidget(self.ch116, 3, 0, 1, 1)
        
        self.ch117 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch117.setObjectName("ch117")
        self.gridLayout.addWidget(self.ch117, 3, 1, 1, 1)
        
        self.ch118 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch118.setObjectName("ch118")
        self.gridLayout.addWidget(self.ch118, 3, 3, 1, 1)
        
        self.ch119 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch119.setObjectName("ch119")
        self.gridLayout.addWidget(self.ch119, 3, 4, 1, 1)
        
        self.ch120 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch120.setObjectName("ch120")
        self.gridLayout.addWidget(self.ch120, 3, 5, 1, 1)
        
        self.ch121 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch121.setObjectName("ch121")
        self.gridLayout.addWidget(self.ch121, 4, 0, 1, 1)
        
        self.ch122 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch122.setObjectName("ch122")
        self.gridLayout.addWidget(self.ch122, 4, 1, 1, 1)
        
        self.ch123 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch123.setObjectName("ch123")
        self.gridLayout.addWidget(self.ch123, 4, 3, 1, 1)
        
        self.ch124 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch124.setObjectName("ch124")
        self.gridLayout.addWidget(self.ch124, 4, 4, 1, 1)
        
        self.ch125 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch125.setObjectName("ch125")
        self.gridLayout.addWidget(self.ch125, 4, 5, 1, 1)
        
        self.ch126 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch126.setObjectName("ch126")
        self.gridLayout.addWidget(self.ch126, 5, 0, 1, 1)
        
        self.ch127 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch127.setObjectName("ch127")
        self.gridLayout.addWidget(self.ch127, 5, 1, 1, 1)
        
        self.ch128 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch128.setObjectName("ch128")
        self.gridLayout.addWidget(self.ch128, 5, 3, 1, 1)
        
        self.ch129 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch129.setObjectName("ch129")
        self.gridLayout.addWidget(self.ch129, 5, 4, 1, 1)
        
        self.ch130 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ch130.setObjectName("ch130")
        self.gridLayout.addWidget(self.ch130, 5, 5, 1, 1)
        
        self.ch201 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch201.setObjectName("ch201")
        self.gridLayout_2.addWidget(self.ch201, 0, 0, 1, 1)
        
        self.ch202 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch202.setObjectName("ch202")
        self.gridLayout_2.addWidget(self.ch202, 0, 1, 1, 1)
        
        self.ch203 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch203.setObjectName("ch203")
        self.gridLayout_2.addWidget(self.ch203, 0, 3, 1, 1)
        
        self.ch204 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch204.setObjectName("ch204")
        self.gridLayout_2.addWidget(self.ch204, 0, 4, 1, 1)
        
        self.ch205 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch205.setObjectName("ch205")
        self.gridLayout_2.addWidget(self.ch205, 0, 5, 1, 1)
        
        self.ch206 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch206.setObjectName("ch206")
        self.gridLayout_2.addWidget(self.ch206, 1, 0, 1, 1)
        
        self.ch207 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch207.setObjectName("ch207")
        self.gridLayout_2.addWidget(self.ch207, 1, 1, 1, 1)
        
        self.ch208 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch208.setObjectName("ch208")
        self.gridLayout_2.addWidget(self.ch208, 1, 3, 1, 1)
        
        self.ch209 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch209.setObjectName("ch209")
        self.gridLayout_2.addWidget(self.ch209, 1, 4, 1, 1)
        
        self.ch210 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch210.setObjectName("ch210")
        self.gridLayout_2.addWidget(self.ch210, 1, 5, 1, 1)
        
        self.ch211 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch211.setObjectName("ch211")
        self.gridLayout_2.addWidget(self.ch211, 2, 0, 1, 1)

        self.ch212 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch212.setObjectName("ch212")
        self.gridLayout_2.addWidget(self.ch212, 2, 1, 1, 1)
        
        self.ch213 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch213.setObjectName("ch213")
        self.gridLayout_2.addWidget(self.ch213, 2, 3, 1, 1)
        
        self.ch214 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch214.setObjectName("ch214")
        self.gridLayout_2.addWidget(self.ch214, 2, 4, 1, 1)
        
        self.ch215 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch215.setObjectName("ch215")
        self.gridLayout_2.addWidget(self.ch215, 2, 5, 1, 1)
        
        self.ch216 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch216.setObjectName("ch216")
        self.gridLayout_2.addWidget(self.ch216, 3, 0, 1, 1)
        
        self.ch217 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch217.setObjectName("ch217")
        self.gridLayout_2.addWidget(self.ch217, 3, 1, 1, 1)
        
        self.ch218 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch218.setObjectName("ch218")
        self.gridLayout_2.addWidget(self.ch218, 3, 3, 1, 1)
        
        self.ch219 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch219.setObjectName("ch219")
        self.gridLayout_2.addWidget(self.ch219, 3, 4, 1, 1)
        
        self.ch220 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch220.setObjectName("ch220")
        self.gridLayout_2.addWidget(self.ch220, 3, 5, 1, 1)
        
        self.ch221 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch221.setObjectName("ch221")
        self.gridLayout_2.addWidget(self.ch221, 4, 0, 1, 1)
        
        self.ch222 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch222.setObjectName("ch222")
        self.gridLayout_2.addWidget(self.ch222, 4, 1, 1, 1)
        
        self.ch223 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch223.setObjectName("ch223")
        self.gridLayout_2.addWidget(self.ch223, 4, 3, 1, 1)
        
        self.ch224 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch224.setObjectName("ch224")
        self.gridLayout_2.addWidget(self.ch224, 4, 4, 1, 1)
        
        self.ch225 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch225.setObjectName("ch225")
        self.gridLayout_2.addWidget(self.ch225, 4, 5, 1, 1)
        
        self.ch226 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch226.setObjectName("ch226")
        self.gridLayout_2.addWidget(self.ch226, 5, 0, 1, 1)
        
        self.ch227 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch227.setObjectName("ch227")
        self.gridLayout_2.addWidget(self.ch227, 5, 1, 1, 1)
        
        self.ch228 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch228.setObjectName("ch228")
        self.gridLayout_2.addWidget(self.ch228, 5, 3, 1, 1)
        
        self.ch229 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch229.setObjectName("ch229")
        self.gridLayout_2.addWidget(self.ch229, 5, 4, 1, 1)
        
        self.ch230 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.ch230.setObjectName("ch230")
        self.gridLayout_2.addWidget(self.ch230, 5, 5, 1, 1)
        
        
        self.ch301 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch301.setObjectName("ch301")
        self.gridLayout_3.addWidget(self.ch301, 0, 0, 1, 1)
        
        self.ch302 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch302.setObjectName("ch302")
        self.gridLayout_3.addWidget(self.ch302, 0, 1, 1, 1)
        
        self.ch303 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch303.setObjectName("ch303")
        self.gridLayout_3.addWidget(self.ch303, 0, 3, 1, 1)
        
        self.ch304 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch304.setObjectName("ch304")
        self.gridLayout_3.addWidget(self.ch304, 0, 4, 1, 1)
        
        self.ch305 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch305.setObjectName("ch305")
        self.gridLayout_3.addWidget(self.ch305, 0, 5, 1, 1)
        
        self.ch306 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch306.setObjectName("ch306")
        self.gridLayout_3.addWidget(self.ch306, 1, 0, 1, 1)
        
        self.ch307 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch307.setObjectName("ch307")
        self.gridLayout_3.addWidget(self.ch307, 1, 1, 1, 1)
        
        self.ch308 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch308.setObjectName("ch308")
        self.gridLayout_3.addWidget(self.ch308, 1, 3, 1, 1)
        
        self.ch309 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch309.setObjectName("ch309")
        self.gridLayout_3.addWidget(self.ch309, 1, 4, 1, 1)
        
        self.ch310 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch310.setObjectName("ch310")
        self.gridLayout_3.addWidget(self.ch310, 1, 5, 1, 1)
        
        self.ch311 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch311.setObjectName("ch311")
        self.gridLayout_3.addWidget(self.ch311, 2, 0, 1, 1)
        
        self.ch312 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch312.setObjectName("ch312")
        self.gridLayout_3.addWidget(self.ch312, 2, 1, 1, 1)
        
        self.ch313 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch313.setObjectName("ch313")
        self.gridLayout_3.addWidget(self.ch313, 2, 3, 1, 1)
        
        self.ch314 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch314.setObjectName("ch314")
        self.gridLayout_3.addWidget(self.ch314, 2, 4, 1, 1)
        
        self.ch315 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch315.setObjectName("ch315")
        self.gridLayout_3.addWidget(self.ch315, 2, 5, 1, 1)
        
        self.ch316 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch316.setObjectName("ch316")
        self.gridLayout_3.addWidget(self.ch316, 3, 0, 1, 1)
        
        self.ch317 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch317.setObjectName("ch317")
        self.gridLayout_3.addWidget(self.ch317, 3, 1, 1, 1)
        
        self.ch318 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch318.setObjectName("ch318")
        self.gridLayout_3.addWidget(self.ch318, 3, 3, 1, 1)
        
        self.ch319 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch319.setObjectName("ch319")
        self.gridLayout_3.addWidget(self.ch319, 3, 4, 1, 1)
        
        self.ch320 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch320.setObjectName("ch320")
        self.gridLayout_3.addWidget(self.ch320, 3, 5, 1, 1)
        
        self.ch321 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch321.setObjectName("ch321")
        self.gridLayout_3.addWidget(self.ch321, 4, 0, 1, 1)
        
        self.ch322 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch322.setObjectName("ch322")
        self.gridLayout_3.addWidget(self.ch322, 4, 1, 1, 1)
        
        self.ch323 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch323.setObjectName("ch323")
        self.gridLayout_3.addWidget(self.ch323, 4, 3, 1, 1)
        
        self.ch324 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch324.setObjectName("ch324")
        self.gridLayout_3.addWidget(self.ch324, 4, 4, 1, 1)
        
        self.ch325 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch325.setObjectName("ch325")
        self.gridLayout_3.addWidget(self.ch325, 4, 5, 1, 1)
        
        self.ch326 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch326.setObjectName("ch326")
        self.gridLayout_3.addWidget(self.ch326, 5, 0, 1, 1)
        
        self.ch327 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch327.setObjectName("ch327")
        self.gridLayout_3.addWidget(self.ch327, 5, 1, 1, 1)
        
        self.ch328 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch328.setObjectName("ch328")
        self.gridLayout_3.addWidget(self.ch328, 5, 3, 1, 1)
        
        self.ch329 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch329.setObjectName("ch329")
        self.gridLayout_3.addWidget(self.ch329, 5, 4, 1, 1)
        
        self.ch330 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ch330.setObjectName("ch330")
        self.gridLayout_3.addWidget(self.ch330, 5, 5, 1, 1)
        
        
        self.ch401 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch401.setObjectName("ch401")
        self.gridLayout_4.addWidget(self.ch401, 0, 0, 1, 1)
        
        self.ch402 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch402.setObjectName("ch402")
        self.gridLayout_4.addWidget(self.ch402, 0, 1, 1, 1)
        
        self.ch403 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch403.setObjectName("ch403")
        self.gridLayout_4.addWidget(self.ch403, 0, 3, 1, 1)
        
        self.ch404 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch404.setObjectName("ch404")
        self.gridLayout_4.addWidget(self.ch404, 0, 4, 1, 1)
        
        self.ch405 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch405.setObjectName("ch405")
        self.gridLayout_4.addWidget(self.ch405, 0, 5, 1, 1)
        
        self.ch406 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch406.setObjectName("ch406")
        self.gridLayout_4.addWidget(self.ch406, 1, 0, 1, 1)
        
        self.ch407 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch407.setObjectName("ch407")
        self.gridLayout_4.addWidget(self.ch407, 1, 1, 1, 1)
        
        self.ch408 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch408.setObjectName("ch408")
        self.gridLayout_4.addWidget(self.ch408, 1, 3, 1, 1)
        
        self.ch409 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch409.setObjectName("ch409")
        self.gridLayout_4.addWidget(self.ch409, 1, 4, 1, 1)
        
        self.ch410 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch410.setObjectName("ch410")
        self.gridLayout_4.addWidget(self.ch410, 1, 5, 1, 1)
        
        self.ch411 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch411.setObjectName("ch411")
        self.gridLayout_4.addWidget(self.ch411, 2, 0, 1, 1)
        
        self.ch412 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch412.setObjectName("ch412")
        self.gridLayout_4.addWidget(self.ch412, 2, 1, 1, 1)
        
        self.ch413 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch413.setObjectName("ch413")
        self.gridLayout_4.addWidget(self.ch413, 2, 3, 1, 1)
        
        self.ch414 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch414.setObjectName("ch414")
        self.gridLayout_4.addWidget(self.ch414, 2, 4, 1, 1)
        
        self.ch415 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch415.setObjectName("ch415")
        self.gridLayout_4.addWidget(self.ch415, 2, 5, 1, 1)
        
        self.ch416 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch416.setObjectName("ch416")
        self.gridLayout_4.addWidget(self.ch416, 3, 0, 1, 1)
        
        self.ch417 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch417.setObjectName("ch417")
        self.gridLayout_4.addWidget(self.ch417, 3, 1, 1, 1)
        
        self.ch418 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch418.setObjectName("ch418")
        self.gridLayout_4.addWidget(self.ch418, 3, 3, 1, 1)
        
        self.ch419 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch419.setObjectName("ch419")
        self.gridLayout_4.addWidget(self.ch419, 3, 4, 1, 1)
        
        self.ch420 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch420.setObjectName("ch420")
        self.gridLayout_4.addWidget(self.ch420, 3, 5, 1, 1)
        
        self.ch421 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch421.setObjectName("ch421")
        self.gridLayout_4.addWidget(self.ch421, 4, 0, 1, 1)
        
        self.ch422 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch422.setObjectName("ch422")
        self.gridLayout_4.addWidget(self.ch422, 4, 1, 1, 1)
        
        self.ch423 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch423.setObjectName("ch423")
        self.gridLayout_4.addWidget(self.ch423, 4, 3, 1, 1)
        
        self.ch424 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch424.setObjectName("ch424")
        self.gridLayout_4.addWidget(self.ch424, 4, 4, 1, 1)
        
        self.ch425 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch425.setObjectName("ch425")
        self.gridLayout_4.addWidget(self.ch425, 4, 5, 1, 1)
        
        self.ch426 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch426.setObjectName("ch426")
        self.gridLayout_4.addWidget(self.ch426, 5, 0, 1, 1)
        
        self.ch427 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch427.setObjectName("ch427")
        self.gridLayout_4.addWidget(self.ch427, 5, 1, 1, 1)
        
        self.ch428 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch428.setObjectName("ch428")
        self.gridLayout_4.addWidget(self.ch428, 5, 3, 1, 1)
        
        self.ch429 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch429.setObjectName("ch429")
        self.gridLayout_4.addWidget(self.ch429, 5, 4, 1, 1)
        
        self.ch430 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.ch430.setObjectName("ch430")
        self.gridLayout_4.addWidget(self.ch430, 5, 5, 1, 1)  
        
        
        self.ch501 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch501.setObjectName("ch501")
        self.gridLayout_5.addWidget(self.ch501, 0, 0, 1, 1)
        
        self.ch502 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch502.setObjectName("ch502")
        self.gridLayout_5.addWidget(self.ch502, 0, 1, 1, 1)
        
        self.ch503 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch503.setObjectName("ch503")
        self.gridLayout_5.addWidget(self.ch503, 0, 3, 1, 1)
        
        self.ch504 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch504.setObjectName("ch504")
        self.gridLayout_5.addWidget(self.ch504, 0, 4, 1, 1)
        
        self.ch505 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch505.setObjectName("ch505")
        self.gridLayout_5.addWidget(self.ch505, 0, 5, 1, 1)
        
        self.ch506 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch506.setObjectName("ch506")
        self.gridLayout_5.addWidget(self.ch506, 1, 0, 1, 1)
        
        self.ch507 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch507.setObjectName("ch507")
        self.gridLayout_5.addWidget(self.ch507, 1, 1, 1, 1)
        
        self.ch508 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch508.setObjectName("ch508")
        self.gridLayout_5.addWidget(self.ch508, 1, 3, 1, 1)
        
        self.ch509 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch509.setObjectName("ch509")
        self.gridLayout_5.addWidget(self.ch509, 1, 4, 1, 1)
        
        self.ch510 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch510.setObjectName("ch510")
        self.gridLayout_5.addWidget(self.ch510, 1, 5, 1, 1)
        
        self.ch511 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch511.setObjectName("ch511")
        self.gridLayout_5.addWidget(self.ch511, 2, 0, 1, 1)
        
        self.ch512 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch512.setObjectName("ch512")
        self.gridLayout_5.addWidget(self.ch512, 2, 1, 1, 1)
        
        self.ch513 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch513.setObjectName("ch513")
        self.gridLayout_5.addWidget(self.ch513, 2, 3, 1, 1)
        
        self.ch514 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch514.setObjectName("ch514")
        self.gridLayout_5.addWidget(self.ch514, 2, 4, 1, 1)
        
        self.ch515 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch515.setObjectName("ch515")
        self.gridLayout_5.addWidget(self.ch515, 2, 5, 1, 1)
        
        self.ch516 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch516.setObjectName("ch516")
        self.gridLayout_5.addWidget(self.ch516, 3, 0, 1, 1)
        
        self.ch517 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch517.setObjectName("ch517")
        self.gridLayout_5.addWidget(self.ch517, 3, 1, 1, 1)
        
        self.ch518 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch518.setObjectName("ch518")
        self.gridLayout_5.addWidget(self.ch518, 3, 3, 1, 1)
        
        self.ch519 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch519.setObjectName("ch519")
        self.gridLayout_5.addWidget(self.ch519, 3, 4, 1, 1)
        
        self.ch520 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch520.setObjectName("ch520")
        self.gridLayout_5.addWidget(self.ch520, 3, 5, 1, 1)
        
        self.ch521 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch521.setObjectName("ch521")
        self.gridLayout_5.addWidget(self.ch521, 4, 0, 1, 1)
        
        self.ch522 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch522.setObjectName("ch522")
        self.gridLayout_5.addWidget(self.ch522, 4, 1, 1, 1)
        
        self.ch523 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch523.setObjectName("ch523")
        self.gridLayout_5.addWidget(self.ch523, 4, 3, 1, 1)
        
        self.ch524 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch524.setObjectName("ch524")
        self.gridLayout_5.addWidget(self.ch524, 4, 4, 1, 1)
        
        self.ch525 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch525.setObjectName("ch525")
        self.gridLayout_5.addWidget(self.ch525, 4, 5, 1, 1)
        
        self.ch526 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch526.setObjectName("ch526")
        self.gridLayout_5.addWidget(self.ch526, 5, 0, 1, 1)
        
        self.ch527 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch527.setObjectName("ch527")
        self.gridLayout_5.addWidget(self.ch527, 5, 1, 1, 1)
        
        self.ch528 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch528.setObjectName("ch528")
        self.gridLayout_5.addWidget(self.ch528, 5, 3, 1, 1)
        
        self.ch529 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch529.setObjectName("ch529")
        self.gridLayout_5.addWidget(self.ch529, 5, 4, 1, 1)
        
        self.ch530 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.ch530.setObjectName("ch530")
        self.gridLayout_5.addWidget(self.ch530, 5, 5, 1, 1)
        
        
        self.ch001 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch001.setObjectName("ch001")
        self.gridLayout_6.addWidget(self.ch001, 0, 0, 1, 1)
        
        self.ch002 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch002.setObjectName("ch002")
        self.gridLayout_6.addWidget(self.ch002, 0, 1, 1, 1)
        
        self.ch003 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch003.setObjectName("ch003")
        self.gridLayout_6.addWidget(self.ch003, 0, 3, 1, 1)
        
        self.ch004 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch004.setObjectName("ch004")
        self.gridLayout_6.addWidget(self.ch004, 0, 4, 1, 1)
        
        self.ch005 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch005.setObjectName("ch005")
        self.gridLayout_6.addWidget(self.ch005, 0, 5, 1, 1)
        
        self.ch006 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch006.setObjectName("ch006")
        self.gridLayout_6.addWidget(self.ch006, 1, 0, 1, 1)
        
        self.ch007 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch007.setObjectName("ch007")
        self.gridLayout_6.addWidget(self.ch007, 1, 1, 1, 1)
        
        self.ch008 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch008.setObjectName("ch008")
        self.gridLayout_6.addWidget(self.ch008, 1, 3, 1, 1)
        
        self.ch009 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch009.setObjectName("ch009")
        self.gridLayout_6.addWidget(self.ch009, 1, 4, 1, 1)
        
        self.ch010 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch010.setObjectName("ch010")
        self.gridLayout_6.addWidget(self.ch010, 1, 5, 1, 1)
        
        self.ch011 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch011.setObjectName("ch011")
        self.gridLayout_6.addWidget(self.ch011, 2, 0, 1, 1)
        
        self.ch012 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch012.setObjectName("ch012")
        self.gridLayout_6.addWidget(self.ch012, 2, 1, 1, 1)
        
        self.ch013 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch013.setObjectName("ch013")
        self.gridLayout_6.addWidget(self.ch013, 2, 3, 1, 1)
        
        self.ch014 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch014.setObjectName("ch014")
        self.gridLayout_6.addWidget(self.ch014, 2, 4, 1, 1)
        
        self.ch015 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch015.setObjectName("ch015")
        self.gridLayout_6.addWidget(self.ch015, 2, 5, 1, 1)
        
        self.ch016 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch016.setObjectName("ch016")
        self.gridLayout_6.addWidget(self.ch016, 3, 0, 1, 1)
        
        self.ch017 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch017.setObjectName("ch017")
        self.gridLayout_6.addWidget(self.ch017, 3, 1, 1, 1)
        
        self.ch018 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch018.setObjectName("ch018")
        self.gridLayout_6.addWidget(self.ch018, 3, 3, 1, 1)
        
        self.ch019 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch019.setObjectName("ch019")
        self.gridLayout_6.addWidget(self.ch019, 3, 4, 1, 1)
        
        self.ch020 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch020.setObjectName("ch020")
        self.gridLayout_6.addWidget(self.ch020, 3, 5, 1, 1)
        
        self.ch021 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch021.setObjectName("ch021")
        self.gridLayout_6.addWidget(self.ch021, 4, 0, 1, 1)
        
        self.ch022 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch022.setObjectName("ch022")
        self.gridLayout_6.addWidget(self.ch022, 4, 1, 1, 1)
        
        self.ch023 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch023.setObjectName("ch023")
        self.gridLayout_6.addWidget(self.ch023, 4, 3, 1, 1)
        
        self.ch024 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch024.setObjectName("ch024")
        self.gridLayout_6.addWidget(self.ch024, 4, 4, 1, 1)
        
        self.ch025 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch025.setObjectName("ch025")
        self.gridLayout_6.addWidget(self.ch025, 4, 5, 1, 1)
        
        self.ch026 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch026.setObjectName("ch026")
        self.gridLayout_6.addWidget(self.ch026, 5, 0, 1, 1)
        
        self.ch027 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch027.setObjectName("ch027")
        self.gridLayout_6.addWidget(self.ch027, 5, 1, 1, 1)
        
        self.ch028 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch028.setObjectName("ch028")
        self.gridLayout_6.addWidget(self.ch028, 5, 3, 1, 1)
        
        self.ch029 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch029.setObjectName("ch029")
        self.gridLayout_6.addWidget(self.ch029, 5, 4, 1, 1)
        
        self.ch030 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ch030.setObjectName("ch030")
        self.gridLayout_6.addWidget(self.ch030, 5, 5, 1, 1)
        
        self.names = QtWidgets.QPushButton(self.centralwidget)
        self.names.setGeometry(QtCore.QRect(328, 550, 85, 23))
        self.names.setObjectName("names")
        
        self.ch101.clicked.connect(lambda: self.bufferAppend(101))
        self.ch102.clicked.connect(lambda: self.bufferAppend(102))
        self.ch103.clicked.connect(lambda: self.bufferAppend(103))
        self.ch104.clicked.connect(lambda: self.bufferAppend(104))
        self.ch105.clicked.connect(lambda: self.bufferAppend(105))
        self.ch106.clicked.connect(lambda: self.bufferAppend(106))
        self.ch107.clicked.connect(lambda: self.bufferAppend(107))
        self.ch108.clicked.connect(lambda: self.bufferAppend(108))
        self.ch109.clicked.connect(lambda: self.bufferAppend(109))
        self.ch110.clicked.connect(lambda: self.bufferAppend(110))
        self.ch111.clicked.connect(lambda: self.bufferAppend(111))
        self.ch112.clicked.connect(lambda: self.bufferAppend(112))
        self.ch113.clicked.connect(lambda: self.bufferAppend(113))
        self.ch114.clicked.connect(lambda: self.bufferAppend(114))
        self.ch115.clicked.connect(lambda: self.bufferAppend(115))
        self.ch116.clicked.connect(lambda: self.bufferAppend(116))
        self.ch117.clicked.connect(lambda: self.bufferAppend(117))
        self.ch118.clicked.connect(lambda: self.bufferAppend(118))
        self.ch119.clicked.connect(lambda: self.bufferAppend(119))
        self.ch120.clicked.connect(lambda: self.bufferAppend(120))
        self.ch121.clicked.connect(lambda: self.bufferAppend(121))
        self.ch122.clicked.connect(lambda: self.bufferAppend(122))
        self.ch123.clicked.connect(lambda: self.bufferAppend(123))
        self.ch124.clicked.connect(lambda: self.bufferAppend(124))
        self.ch125.clicked.connect(lambda: self.bufferAppend(125))
        self.ch126.clicked.connect(lambda: self.bufferAppend(126))
        self.ch127.clicked.connect(lambda: self.bufferAppend(127))
        self.ch128.clicked.connect(lambda: self.bufferAppend(128))
        self.ch129.clicked.connect(lambda: self.bufferAppend(129))
        self.ch130.clicked.connect(lambda: self.bufferAppend(130))
        
        self.ch201.clicked.connect(lambda: self.bufferAppend(201))
        self.ch202.clicked.connect(lambda: self.bufferAppend(202))
        self.ch203.clicked.connect(lambda: self.bufferAppend(203))
        self.ch204.clicked.connect(lambda: self.bufferAppend(204))
        self.ch205.clicked.connect(lambda: self.bufferAppend(205))
        self.ch206.clicked.connect(lambda: self.bufferAppend(206))
        self.ch207.clicked.connect(lambda: self.bufferAppend(207))
        self.ch208.clicked.connect(lambda: self.bufferAppend(208))
        self.ch209.clicked.connect(lambda: self.bufferAppend(209))
        self.ch210.clicked.connect(lambda: self.bufferAppend(210))
        self.ch211.clicked.connect(lambda: self.bufferAppend(211))
        self.ch212.clicked.connect(lambda: self.bufferAppend(212))
        self.ch213.clicked.connect(lambda: self.bufferAppend(213))
        self.ch214.clicked.connect(lambda: self.bufferAppend(214))
        self.ch215.clicked.connect(lambda: self.bufferAppend(215))
        self.ch216.clicked.connect(lambda: self.bufferAppend(216))
        self.ch217.clicked.connect(lambda: self.bufferAppend(217))
        self.ch218.clicked.connect(lambda: self.bufferAppend(218))
        self.ch219.clicked.connect(lambda: self.bufferAppend(219))
        self.ch220.clicked.connect(lambda: self.bufferAppend(220))
        self.ch221.clicked.connect(lambda: self.bufferAppend(221))
        self.ch222.clicked.connect(lambda: self.bufferAppend(222))
        self.ch223.clicked.connect(lambda: self.bufferAppend(223))
        self.ch224.clicked.connect(lambda: self.bufferAppend(224))
        self.ch225.clicked.connect(lambda: self.bufferAppend(225))
        self.ch226.clicked.connect(lambda: self.bufferAppend(226))
        self.ch227.clicked.connect(lambda: self.bufferAppend(227))
        self.ch228.clicked.connect(lambda: self.bufferAppend(228))
        self.ch229.clicked.connect(lambda: self.bufferAppend(229))
        self.ch230.clicked.connect(lambda: self.bufferAppend(230))
        
        self.ch301.clicked.connect(lambda: self.bufferAppend(301))
        self.ch302.clicked.connect(lambda: self.bufferAppend(302))
        self.ch303.clicked.connect(lambda: self.bufferAppend(303))
        self.ch304.clicked.connect(lambda: self.bufferAppend(304))
        self.ch305.clicked.connect(lambda: self.bufferAppend(305))
        self.ch306.clicked.connect(lambda: self.bufferAppend(306))
        self.ch307.clicked.connect(lambda: self.bufferAppend(307))
        self.ch308.clicked.connect(lambda: self.bufferAppend(308))
        self.ch309.clicked.connect(lambda: self.bufferAppend(309))
        self.ch310.clicked.connect(lambda: self.bufferAppend(310))
        self.ch311.clicked.connect(lambda: self.bufferAppend(311))
        self.ch312.clicked.connect(lambda: self.bufferAppend(312))
        self.ch313.clicked.connect(lambda: self.bufferAppend(313))
        self.ch314.clicked.connect(lambda: self.bufferAppend(314))
        self.ch315.clicked.connect(lambda: self.bufferAppend(315))
        self.ch316.clicked.connect(lambda: self.bufferAppend(316))
        self.ch317.clicked.connect(lambda: self.bufferAppend(317))
        self.ch318.clicked.connect(lambda: self.bufferAppend(318))
        self.ch319.clicked.connect(lambda: self.bufferAppend(319))
        self.ch320.clicked.connect(lambda: self.bufferAppend(320))
        self.ch321.clicked.connect(lambda: self.bufferAppend(321))
        self.ch322.clicked.connect(lambda: self.bufferAppend(322))
        self.ch323.clicked.connect(lambda: self.bufferAppend(323))
        self.ch324.clicked.connect(lambda: self.bufferAppend(324))
        self.ch325.clicked.connect(lambda: self.bufferAppend(325))
        self.ch326.clicked.connect(lambda: self.bufferAppend(326))
        self.ch327.clicked.connect(lambda: self.bufferAppend(327))
        self.ch328.clicked.connect(lambda: self.bufferAppend(328))
        self.ch329.clicked.connect(lambda: self.bufferAppend(329))
        self.ch330.clicked.connect(lambda: self.bufferAppend(330))
        
        self.ch401.clicked.connect(lambda: self.bufferAppend(401))
        self.ch402.clicked.connect(lambda: self.bufferAppend(402))
        self.ch403.clicked.connect(lambda: self.bufferAppend(403))
        self.ch404.clicked.connect(lambda: self.bufferAppend(404))
        self.ch405.clicked.connect(lambda: self.bufferAppend(405))
        self.ch406.clicked.connect(lambda: self.bufferAppend(406))
        self.ch407.clicked.connect(lambda: self.bufferAppend(407))
        self.ch408.clicked.connect(lambda: self.bufferAppend(408))
        self.ch409.clicked.connect(lambda: self.bufferAppend(409))
        self.ch410.clicked.connect(lambda: self.bufferAppend(410))
        self.ch411.clicked.connect(lambda: self.bufferAppend(411))
        self.ch412.clicked.connect(lambda: self.bufferAppend(412))
        self.ch413.clicked.connect(lambda: self.bufferAppend(413))
        self.ch414.clicked.connect(lambda: self.bufferAppend(414))
        self.ch415.clicked.connect(lambda: self.bufferAppend(415))
        self.ch416.clicked.connect(lambda: self.bufferAppend(416))
        self.ch417.clicked.connect(lambda: self.bufferAppend(417))
        self.ch418.clicked.connect(lambda: self.bufferAppend(418))
        self.ch419.clicked.connect(lambda: self.bufferAppend(419))
        self.ch420.clicked.connect(lambda: self.bufferAppend(420))
        self.ch421.clicked.connect(lambda: self.bufferAppend(421))
        self.ch422.clicked.connect(lambda: self.bufferAppend(422))
        self.ch423.clicked.connect(lambda: self.bufferAppend(423))
        self.ch424.clicked.connect(lambda: self.bufferAppend(424))
        self.ch425.clicked.connect(lambda: self.bufferAppend(425))
        self.ch426.clicked.connect(lambda: self.bufferAppend(426))
        self.ch427.clicked.connect(lambda: self.bufferAppend(427))
        self.ch428.clicked.connect(lambda: self.bufferAppend(428))
        self.ch429.clicked.connect(lambda: self.bufferAppend(429))
        self.ch430.clicked.connect(lambda: self.bufferAppend(430))
        
        self.ch501.clicked.connect(lambda: self.bufferAppend(501))
        self.ch502.clicked.connect(lambda: self.bufferAppend(502))
        self.ch503.clicked.connect(lambda: self.bufferAppend(503))
        self.ch504.clicked.connect(lambda: self.bufferAppend(504))
        self.ch505.clicked.connect(lambda: self.bufferAppend(505))
        self.ch506.clicked.connect(lambda: self.bufferAppend(506))
        self.ch507.clicked.connect(lambda: self.bufferAppend(507))
        self.ch508.clicked.connect(lambda: self.bufferAppend(508))
        self.ch509.clicked.connect(lambda: self.bufferAppend(509))
        self.ch510.clicked.connect(lambda: self.bufferAppend(510))
        self.ch511.clicked.connect(lambda: self.bufferAppend(511))
        self.ch512.clicked.connect(lambda: self.bufferAppend(512))
        self.ch513.clicked.connect(lambda: self.bufferAppend(513))
        self.ch514.clicked.connect(lambda: self.bufferAppend(514))
        self.ch515.clicked.connect(lambda: self.bufferAppend(515))
        self.ch516.clicked.connect(lambda: self.bufferAppend(516))
        self.ch517.clicked.connect(lambda: self.bufferAppend(517))
        self.ch518.clicked.connect(lambda: self.bufferAppend(518))
        self.ch519.clicked.connect(lambda: self.bufferAppend(519))
        self.ch520.clicked.connect(lambda: self.bufferAppend(520))
        self.ch521.clicked.connect(lambda: self.bufferAppend(521))
        self.ch522.clicked.connect(lambda: self.bufferAppend(522))
        self.ch523.clicked.connect(lambda: self.bufferAppend(523))
        self.ch524.clicked.connect(lambda: self.bufferAppend(524))
        self.ch525.clicked.connect(lambda: self.bufferAppend(525))
        self.ch526.clicked.connect(lambda: self.bufferAppend(526))
        self.ch527.clicked.connect(lambda: self.bufferAppend(527))
        self.ch528.clicked.connect(lambda: self.bufferAppend(528))
        self.ch529.clicked.connect(lambda: self.bufferAppend(529))
        self.ch530.clicked.connect(lambda: self.bufferAppend(530))
        
        self.ch001.clicked.connect(lambda: self.bufferAppend(1))
        self.ch002.clicked.connect(lambda: self.bufferAppend(2))
        self.ch003.clicked.connect(lambda: self.bufferAppend(3))
        self.ch004.clicked.connect(lambda: self.bufferAppend(4))
        self.ch005.clicked.connect(lambda: self.bufferAppend(5))
        self.ch006.clicked.connect(lambda: self.bufferAppend(6))
        self.ch007.clicked.connect(lambda: self.bufferAppend(7))
        self.ch008.clicked.connect(lambda: self.bufferAppend(8))
        self.ch009.clicked.connect(lambda: self.bufferAppend(9))
        self.ch010.clicked.connect(lambda: self.bufferAppend(10))
        self.ch011.clicked.connect(lambda: self.bufferAppend(11))
        self.ch012.clicked.connect(lambda: self.bufferAppend(12))
        self.ch013.clicked.connect(lambda: self.bufferAppend(13))
        self.ch014.clicked.connect(lambda: self.bufferAppend(14))
        self.ch015.clicked.connect(lambda: self.bufferAppend(15))
        self.ch016.clicked.connect(lambda: self.bufferAppend(16))
        self.ch017.clicked.connect(lambda: self.bufferAppend(17))
        self.ch018.clicked.connect(lambda: self.bufferAppend(18))
        self.ch019.clicked.connect(lambda: self.bufferAppend(19))
        self.ch020.clicked.connect(lambda: self.bufferAppend(20))
        self.ch021.clicked.connect(lambda: self.bufferAppend(21))
        self.ch022.clicked.connect(lambda: self.bufferAppend(22))
        self.ch023.clicked.connect(lambda: self.bufferAppend(23))
        self.ch024.clicked.connect(lambda: self.bufferAppend(24))
        self.ch025.clicked.connect(lambda: self.bufferAppend(25))
        self.ch026.clicked.connect(lambda: self.bufferAppend(26))
        self.ch027.clicked.connect(lambda: self.bufferAppend(27))
        self.ch028.clicked.connect(lambda: self.bufferAppend(28))
        self.ch029.clicked.connect(lambda: self.bufferAppend(29))
        self.ch030.clicked.connect(lambda: self.bufferAppend(30))
        self.names.clicked.connect(lambda: self.openSignalNamesWindow(self.buffer))
        self.su0.clicked.connect(self.mark0)
        self.su1.clicked.connect(self.mark1)
        self.su2.clicked.connect(self.mark2)
        self.su3.clicked.connect(self.mark3)
        self.su4.clicked.connect(self.mark4)
        self.su5.clicked.connect(self.mark5)
        
        self.defaultChannel() #sets to false
    def enterFrequency(self):
        self.enterFreq = QtWidgets.QLabel(self.centralwidget)
        self.enterFreq.setGeometry(845,149,91,16)
        self.enterFreq.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.enterFreq.setObjectName("enterFreq")
        
        self.frequency_e = QtWidgets.QLineEdit(self.centralwidget)
        self.frequency_e.setAlignment(QtCore.Qt.AlignCenter)
        self.frequency_e.setGeometry(QtCore.QRect(815,180, 100, 20))
        self.frequency_e.setObjectName("frequency_e")
        
        self.hz = QtWidgets.QLabel(self.centralwidget)
        self.hz.setGeometry(QtCore.QRect(955,180,30,20))
        self.hz.setObjectName("hz")
    def enterIPAddress(self):
        self.enterIP = QtWidgets.QLabel(self.centralwidget)
        self.enterIP.setGeometry(QtCore.QRect(840, 254, 101, 32))
        self.enterIP.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.enterIP.setObjectName("enterIP")
        
        self.ip1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip1.setGeometry(QtCore.QRect(790, 300, 37, 20))
        self.ip1.setObjectName("ip1")
        self.ip2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip2.setGeometry(QtCore.QRect(842, 300, 37, 20))
        self.ip2.setObjectName("ip2")
        self.ip3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip3.setGeometry(QtCore.QRect(894, 300, 37, 20))
        self.ip3.setObjectName("ip3")
        self.ip4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip4.setGeometry(QtCore.QRect(946, 300, 37, 20))
        self.ip4.setObjectName("ip4")
        self.colon1 = QtWidgets.QLabel(self.centralwidget)
        self.colon1.setGeometry(QtCore.QRect(827, 300, 15, 20))
        self.colon1.setObjectName("colon1")
        self.colon2 = QtWidgets.QLabel(self.centralwidget)
        self.colon2.setGeometry(QtCore.QRect(879, 300, 15, 20))
        self.colon2.setObjectName("colon2")
        self.colon3 = QtWidgets.QLabel(self.centralwidget)
        self.colon3.setGeometry(QtCore.QRect(931, 300, 15, 20))
        self.colon3.setObjectName("colon3")
    def enterDatabase(self):
        self.enterInflux = QtWidgets.QLabel(self.centralwidget)
        self.enterInflux.setGeometry(QtCore.QRect(830, 403, 120, 16))
        self.enterInflux.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.enterInflux.setObjectName("enterInflux")
        
        self.mea_name = QtWidgets.QLabel(self.centralwidget)
        self.mea_name.setGeometry(QtCore.QRect(720, 434, 100, 15))
        self.mea_name.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.mea_name.setObjectName("mea_name")
        
        self.org = QtWidgets.QLabel(self.centralwidget)
        self.org.setGeometry(QtCore.QRect(720, 462, 70, 15))
        self.org.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.org.setObjectName("org")
        
        self.bucket = QtWidgets.QLabel(self.centralwidget)
        self.bucket.setGeometry(QtCore.QRect(720, 489, 45, 15))
        self.bucket.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.bucket.setObjectName("bucket")
        
        self.token = QtWidgets.QLabel(self.centralwidget)
        self.token.setGeometry(QtCore.QRect(720, 517, 35, 15))
        self.token.setStyleSheet("background-color: rgb(0, 0, 127);color:rgb(255,255,255)")
        self.token.setObjectName("token")
        
        self.mea_name_e = QtWidgets.QLineEdit(self.centralwidget)
        self.mea_name_e.setGeometry(QtCore.QRect(990, 434, 70, 15))
        self.mea_name_e.setObjectName("mea_name_e")
        
        self.org_e = QtWidgets.QLineEdit(self.centralwidget)
        self.org_e.setGeometry(QtCore.QRect(970, 462, 90, 15))
        self.org_e.setObjectName("org_e")
        
        self.bucket_e = QtWidgets.QLineEdit(self.centralwidget)
        self.bucket_e.setGeometry(QtCore.QRect(920, 489, 140, 15))
        self.bucket_e.setObjectName("bucket_e")
        
        self.token_e = QtWidgets.QLineEdit(self.centralwidget)
        self.token_e.setGeometry(QtCore.QRect(860, 517, 200, 15))
        self.token_e.setObjectName("token_e")
    
    def chidToItem(self,chid):
        index = (chid%100-1)+int(chid/100)*30 #502 -> 1+5*30=151
        #print(index)
        if index<30:
            item = self.gridLayout_6.itemAt(index).widget()
        elif index<60:
            item = self.gridLayout.itemAt(index-30).widget()
        elif index<90:
            item = self.gridLayout_2.itemAt(index-60).widget()
        elif index<120:
            item = self.gridLayout_3.itemAt(index-90).widget()
        elif index<150:
            item = self.gridLayout_4.itemAt(index-120).widget()
        elif index<180:
            item = self.gridLayout_5.itemAt(index-150).widget()
        
        return index,item 
    
    def bufferAppend(self,chid): ##save selected but not yet saved channel to buffer
        index,item = self.chidToItem(chid)
            
        if self.button_mode[index] == False: 
            self.buffer = np.insert(self.buffer,self.buffer.size,chid)
            self.button_mode[index] = True
            item.setStyleSheet("background-color: rgb(0,0,127);color: rgb(255,255,255)")
            
        elif self.button_mode[index] == True:
            del_index_array = np.where(self.buffer == chid)
            self.buffer = np.delete(self.buffer,del_index_array[0])
            self.button_mode[index] = False
            item.setStyleSheet("background-color: rgb(255,255,255);")
    
    def initProject(self):
        ip_address = str(self.ip1.text()+"."+self.ip2.text()+"."+self.ip3.text()+"."+self.ip4.text())
        runChInformation(ip_address)
        channel_info = pd.read_csv("channel_info_python.csv")
        chinfo = getChannelData(channel_info)
        #----------
        #subunits = getSubUnits(chinfo)
        #channel which are not in chinfo i.e. [001,340,320,421]
        #
        # for chid in channel:
            # index,item = self.chidToItem(chid)
            # item.setEnabled(False)
            # item.hide()
        #----------
        size = int(chinfo.size/15)
        chid = np.array([],int)
        all_channel = np.array([],int)
        
        for i in range(6):
            for j in range(30):
                channel_elem= i*100+j+1
                all_channel = np.append(all_channel,channel_elem)
                
        for i in range(size):
            digit1 = chinfo[2+i*15]-48
            digit2 = chinfo[3+i*15]-48
            digit3 = chinfo[4+i*15]-48
            chid_elem = digit1*100+digit2*10+digit3
            chid = np.append(chid,chid_elem)
        
        
        chid_miss = all_channel
        for i in range(chid.size):
            chid_miss = chid_miss[chid_miss != chid[i]]
        
        for chid_elem in chid_miss: #feature: all missing channels are hidden -> only channel in chinfo are seen
            index,item = self.chidToItem(chid_elem)
            item.setEnabled(False)
            item.hide()
        # for chid_elem in chid: #feature: colors all existing channels depending on their sensor
            # index,item = self.chidToItem(chid_elem)
            # if (chinfo[index*15+5] == 86):  ##if V  #here add mV : index 86->V 85->m
                # item.setStyleSheet
            # elif (chinfo[index*15+6] == 67):  ##if °C
                # item.setStyleSheet
            
    
    def saveProjectName(self):
        self.project_name = self.project_name_e.text()
            
    ##for multiple channel
    def bubbleSort(self,selected_channel):
        for i in selected_channel.size-np.arange(selected_channel.size):
            for j in np.arange(i-1):
                if selected_channel[j]>selected_channel[j+1]:
                    temp = selected_channel[j]
                    selected_channel[j] = selected_channel[j+1]
                    selected_channel[j+1] = temp
        return selected_channel
    
    def setChannel(self): ##after "save" assigns buffer to selected_channel
        self.buffer = self.buffer.astype(int)
        self.selected_channel = self.buffer
        self.selected_channel = self.bubbleSort(self.selected_channel) #gets the channel in the right order
        #self.buffer = np.array([])
        #print(self.buffer) #should print out []
        
        if hasattr(self,'ui_si')==True:
            self.signal_names = self.ui_si.signal_names
        #print(self.selected_channel)
        #print(self.signal_names)
    
    def defaultChannel(self): #to ensure that every button is white and FALSE when opening the window
        for index in np.arange(180):
            if self.button_mode[index]==True:
                self.button_mode[index]=False
                if index<30:
                    item = self.gridLayout_6.itemAt(index).widget()
                elif index<60:
                    item = self.gridLayout.itemAt(index-30).widget()
                elif index<90:
                    item = self.gridLayout_2.itemAt(index-60).widget()
                elif index<120:
                    item = self.gridLayout_3.itemAt(index-90).widget()
                elif index<150:
                    item = self.gridLayout_4.itemAt(index-120).widget()
                elif index<180:
                    item = self.gridLayout_5.itemAt(index-150).widget()
                item.setStyleSheet("background-color: rgb(255,255,255);")
                
    def mark0(self):
        #self.su0.setStyleSheet("background-color: rgb(255, 0, 0);")
        sub = 501
        for i in range(30):
            self.bufferAppend(sub+i)
            
    def mark1(self):
        #self.su1.setStyleSheet("background-color: rgb(255, 0, 0);")
        sub = 1
        for i in range(30):
            self.bufferAppend(sub+i)
        
    def mark2(self):
        #self.su2.setStyleSheet("background-color: rgb(255, 0, 0);")
        sub = 101
        for i in range(30):
            self.bufferAppend(sub+i)
    
    def mark3(self):
        #self.su3.setStyleSheet("background-color: rgb(255, 0, 0);")
        sub = 201
        for i in range(30):
            self.bufferAppend(sub+i)
    
    def mark4(self):
        #self.su4.setStyleSheet("background-color: rgb(255, 0, 0);")
        sub = 301
        for i in range(30):
            self.bufferAppend(sub+i)
    
    def mark5(self):
        #self.su5.setStyleSheet("background-color: rgb(255, 0, 0);")
        sub = 401
        for i in range(30):
            self.bufferAppend(sub+i)
    ##for multiple channel END
    
    ##for frequency START
    def setFrequency(self):
        self.frequency = self.frequency_e.text()
    ##for frequency END
    
    ##for ip-address START
    def setIP(self):
        trd = self.ip3.text()
        if trd=="000":
            trd = "0"
        self.ip_address = str(self.ip1.text()+"."+self.ip2.text()+"."+trd+"."+self.ip4.text())
        print(self.ip_address)
    ##for ip-address END
    
    ##for database START
    def setDatabaseParameter(self):
        self.measurement_name = str(self.mea_name_e.text())
        self.org = str(self.org_e.text())
        self.bucket = str(self.bucket_e.text())
        self.token = str(self.token_e.text())
    ##for database END
    
    def saveProject(self):
        self.save.setEnabled(False)
        self.saveProjectName()
        self.setChannel()
        self.setFrequency()
        self.setIP()
        self.setDatabaseParameter()
        
        self.setProjectSettings()
        parent_dir = "Projects"
        directory = self.project_name
        path = parent_dir+"/"+directory
        os.makedirs(path)
        
        self.createProjectSettingsFile(path)
        
    def setProjectSettings(self):
        self.project_settings=[]
        self.database_settings=[]
        
        print(self.project_name)
        self.project_settings.append(self.project_name)
        self.project_settings.append(self.ip_address)
        self.project_settings.append(float(self.frequency))
        self.project_settings.append(list(self.selected_channel))
        
        if hasattr(self,'ui_si')==True:
            self.signal_names = self.ui_si.signal_names
        
        ##extend signal names to the same length as selected_channel #bug fix
        if self.selected_channel.size != len(self.signal_names):
            diff = self.selected_channel.size - len(self.signal_names)
            for i in np.arange(diff): 
                self.signal_names.append("--")
        ####
        
        self.project_settings.append(self.signal_names)
        
        self.database_settings.append(self.measurement_name)
        self.database_settings.append(self.org)
        self.database_settings.append(self.bucket)
        self.database_settings.append(self.token)
        
        self.project_settings.append(self.database_settings)
            
    def createProjectSettingsFile(self,path):
        filename = path+"/"+"project_settings.proj"
        print(filename)
        f = open(filename,"w")
        print(self.project_settings)
        for settings in self.project_settings:
            f.write(str(settings)+"\n")
        f.close()
        
    def openProject(self):
        self.window = QtWidgets.QMainWindow()
        filename=QtWidgets.QFileDialog.getOpenFileName(self.window,'Open File',r'Projects')
        print(filename[0])
        f = open(filename[0],'r')
        settings = f.read()
        f.close()
        lines = settings.split('\n')
        
        self.project_settings=[] #sets project settings to none
        self.defaultChannel()
        
        self.project_settings.append(lines[0])
        self.project_name_e.setText(lines[0])
        
        self.project_settings.append(lines[1])
        self.ip1.setText(lines[1][:3]) #192
        self.ip2.setText(lines[1][4:7]) #168
        self.ip3.setText(lines[1][8:9]) #0
        self.ip4.setText(lines[1][10:13]) #100
        
        #self.initProject()
        
        self.project_settings.append(float(lines[2]))
        self.frequency_e.setText(str(float(lines[2])))
        
        channel = np.asarray([int(element) for element in lines[3][1:-1].split(', ')])
        self.project_settings.append(channel)
        
        for chid in channel:
            self.bufferAppend(chid)
        
        names = [element[1:-1] for element in lines[4][1:-1].split(', ')]
        self.project_settings.append(names)
        
        datab = [element[1:-1] for element in lines[5][1:-1].split(', ')]
        self.mea_name_e.setText(datab[0])
        self.org_e.setText(datab[1])
        self.bucket_e.setText(datab[2])
        self.token_e.setText(datab[3])
        self.project_settings.append(datab)
        
        
        print("Project Settings:",self.project_settings)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.project_name.setText(_translate("MainWindow","  Project Name"))
        
        self.ch130.setText(_translate("MainWindow", "30"))
        self.ch125.setText(_translate("MainWindow", "25"))
        self.ch119.setText(_translate("MainWindow", "19"))
        self.ch120.setText(_translate("MainWindow", "20"))
        self.ch129.setText(_translate("MainWindow", "29"))
        self.ch122.setText(_translate("MainWindow", "22"))
        self.ch103.setText(_translate("MainWindow", "3"))
        self.ch126.setText(_translate("MainWindow", "26"))
        self.ch124.setText(_translate("MainWindow", "24"))
        self.ch106.setText(_translate("MainWindow", "6"))
        self.ch123.setText(_translate("MainWindow", "23"))
        self.ch117.setText(_translate("MainWindow", "17"))
        self.ch118.setText(_translate("MainWindow", "18"))
        self.ch111.setText(_translate("MainWindow", "11"))
        self.ch105.setText(_translate("MainWindow", "5"))
        self.ch128.setText(_translate("MainWindow", "28"))
        self.ch114.setText(_translate("MainWindow", "14"))
        self.ch127.setText(_translate("MainWindow", "27"))
        self.ch110.setText(_translate("MainWindow", "10"))
        self.ch107.setText(_translate("MainWindow", "7"))
        self.ch113.setText(_translate("MainWindow", "13"))
        self.ch121.setText(_translate("MainWindow", "21"))
        self.ch116.setText(_translate("MainWindow", "16"))
        self.ch108.setText(_translate("MainWindow", "8"))
        self.ch109.setText(_translate("MainWindow", "9"))
        self.ch101.setText(_translate("MainWindow", "1"))
        self.ch112.setText(_translate("MainWindow", "12"))
        self.ch102.setText(_translate("MainWindow", "2"))
        self.ch115.setText(_translate("MainWindow", "15"))
        self.ch104.setText(_translate("MainWindow", "4"))
        self.ch202.setText(_translate("MainWindow", "2"))
        self.ch209.setText(_translate("MainWindow", "9"))
        self.ch212.setText(_translate("MainWindow", "12"))
        self.ch215.setText(_translate("MainWindow", "15"))
        self.ch217.setText(_translate("MainWindow", "17"))
        self.ch214.setText(_translate("MainWindow", "14"))
        self.ch225.setText(_translate("MainWindow", "25"))
        self.ch227.setText(_translate("MainWindow", "27"))
        self.ch204.setText(_translate("MainWindow", "4"))
        self.ch222.setText(_translate("MainWindow", "22"))
        self.ch207.setText(_translate("MainWindow", "7"))
        self.ch224.setText(_translate("MainWindow", "24"))
        self.ch219.setText(_translate("MainWindow", "19"))
        self.ch210.setText(_translate("MainWindow", "10"))
        self.ch228.setText(_translate("MainWindow", "28"))
        self.ch220.setText(_translate("MainWindow", "20"))
        self.ch206.setText(_translate("MainWindow", "6"))
        self.ch229.setText(_translate("MainWindow", "29"))
        self.ch203.setText(_translate("MainWindow", "3"))
        self.ch230.setText(_translate("MainWindow", "30"))
        self.ch211.setText(_translate("MainWindow", "11"))
        self.ch205.setText(_translate("MainWindow", "5"))
        self.ch216.setText(_translate("MainWindow", "16"))
        self.ch218.setText(_translate("MainWindow", "18"))
        self.ch221.setText(_translate("MainWindow", "21"))
        self.ch223.setText(_translate("MainWindow", "23"))
        self.ch213.setText(_translate("MainWindow", "13"))
        self.ch208.setText(_translate("MainWindow", "8"))
        self.ch226.setText(_translate("MainWindow", "26"))
        self.ch201.setText(_translate("MainWindow", "1"))
        self.su1.setText(_translate("MainWindow", "0"))
        self.su2.setText(_translate("MainWindow", "1"))
        self.su3.setText(_translate("MainWindow", "2"))
        self.ch302.setText(_translate("MainWindow", "2"))
        self.ch309.setText(_translate("MainWindow", "9"))
        self.ch312.setText(_translate("MainWindow", "12"))
        self.ch315.setText(_translate("MainWindow", "15"))
        self.ch317.setText(_translate("MainWindow", "17"))
        self.ch314.setText(_translate("MainWindow", "14"))
        self.ch325.setText(_translate("MainWindow", "25"))
        self.ch327.setText(_translate("MainWindow", "27"))
        self.ch304.setText(_translate("MainWindow", "4"))
        self.ch322.setText(_translate("MainWindow", "22"))
        self.ch307.setText(_translate("MainWindow", "7"))
        self.ch324.setText(_translate("MainWindow", "24"))
        self.ch319.setText(_translate("MainWindow", "19"))
        self.ch310.setText(_translate("MainWindow", "10"))
        self.ch328.setText(_translate("MainWindow", "28"))
        self.ch320.setText(_translate("MainWindow", "20"))
        self.ch306.setText(_translate("MainWindow", "6"))
        self.ch329.setText(_translate("MainWindow", "29"))
        self.ch303.setText(_translate("MainWindow", "3"))
        self.ch330.setText(_translate("MainWindow", "30"))
        self.ch311.setText(_translate("MainWindow", "11"))
        self.ch305.setText(_translate("MainWindow", "5"))
        self.ch316.setText(_translate("MainWindow", "16"))
        self.ch318.setText(_translate("MainWindow", "18"))
        self.ch321.setText(_translate("MainWindow", "21"))
        self.ch323.setText(_translate("MainWindow", "23"))
        self.ch313.setText(_translate("MainWindow", "13"))
        self.ch308.setText(_translate("MainWindow", "8"))
        self.ch326.setText(_translate("MainWindow", "26"))
        self.ch301.setText(_translate("MainWindow", "1"))
        self.su4.setText(_translate("MainWindow", "3"))
        self.su5.setText(_translate("MainWindow", "4"))
        self.su0.setText(_translate("MainWindow", "5"))
        self.ch430.setText(_translate("MainWindow", "30"))
        self.ch425.setText(_translate("MainWindow", "25"))
        self.ch419.setText(_translate("MainWindow", "19"))
        self.ch420.setText(_translate("MainWindow", "20"))
        self.ch429.setText(_translate("MainWindow", "29"))
        self.ch422.setText(_translate("MainWindow", "22"))
        self.ch403.setText(_translate("MainWindow", "3"))
        self.ch426.setText(_translate("MainWindow", "26"))
        self.ch424.setText(_translate("MainWindow", "24"))
        self.ch406.setText(_translate("MainWindow", "6"))
        self.ch423.setText(_translate("MainWindow", "23"))
        self.ch417.setText(_translate("MainWindow", "17"))
        self.ch418.setText(_translate("MainWindow", "18"))
        self.ch411.setText(_translate("MainWindow", "11"))
        self.ch405.setText(_translate("MainWindow", "5"))
        self.ch428.setText(_translate("MainWindow", "28"))
        self.ch414.setText(_translate("MainWindow", "14"))
        self.ch427.setText(_translate("MainWindow", "27"))
        self.ch410.setText(_translate("MainWindow", "10"))
        self.ch407.setText(_translate("MainWindow", "7"))
        self.ch413.setText(_translate("MainWindow", "13"))
        self.ch421.setText(_translate("MainWindow", "21"))
        self.ch416.setText(_translate("MainWindow", "16"))
        self.ch408.setText(_translate("MainWindow", "8"))
        self.ch409.setText(_translate("MainWindow", "9"))
        self.ch401.setText(_translate("MainWindow", "1"))
        self.ch412.setText(_translate("MainWindow", "12"))
        self.ch402.setText(_translate("MainWindow", "2"))
        self.ch415.setText(_translate("MainWindow", "15"))
        self.ch404.setText(_translate("MainWindow", "4"))
        self.ch530.setText(_translate("MainWindow", "30"))
        self.ch525.setText(_translate("MainWindow", "25"))
        self.ch519.setText(_translate("MainWindow", "19"))
        self.ch520.setText(_translate("MainWindow", "20"))
        self.ch529.setText(_translate("MainWindow", "29"))
        self.ch522.setText(_translate("MainWindow", "22"))
        self.ch503.setText(_translate("MainWindow", "3"))
        self.ch526.setText(_translate("MainWindow", "26"))
        self.ch524.setText(_translate("MainWindow", "24"))
        self.ch506.setText(_translate("MainWindow", "6"))
        self.ch523.setText(_translate("MainWindow", "23"))
        self.ch517.setText(_translate("MainWindow", "17"))
        self.ch518.setText(_translate("MainWindow", "18"))
        self.ch511.setText(_translate("MainWindow", "11"))
        self.ch505.setText(_translate("MainWindow", "5"))
        self.ch528.setText(_translate("MainWindow", "28"))
        self.ch514.setText(_translate("MainWindow", "14"))
        self.ch527.setText(_translate("MainWindow", "27"))
        self.ch510.setText(_translate("MainWindow", "10"))
        self.ch507.setText(_translate("MainWindow", "7"))
        self.ch513.setText(_translate("MainWindow", "13"))
        self.ch521.setText(_translate("MainWindow", "21"))
        self.ch516.setText(_translate("MainWindow", "16"))
        self.ch508.setText(_translate("MainWindow", "8"))
        self.ch509.setText(_translate("MainWindow", "9"))
        self.ch501.setText(_translate("MainWindow", "1"))
        self.ch512.setText(_translate("MainWindow", "12"))
        self.ch502.setText(_translate("MainWindow", "2"))
        self.ch515.setText(_translate("MainWindow", "15"))
        self.ch504.setText(_translate("MainWindow", "4"))
        self.ch030.setText(_translate("MainWindow", "30"))
        self.ch025.setText(_translate("MainWindow", "25"))
        self.ch019.setText(_translate("MainWindow", "19"))
        self.ch020.setText(_translate("MainWindow", "20"))
        self.ch029.setText(_translate("MainWindow", "29"))
        self.ch022.setText(_translate("MainWindow", "22"))
        self.ch003.setText(_translate("MainWindow", "3"))
        self.ch026.setText(_translate("MainWindow", "26"))
        self.ch024.setText(_translate("MainWindow", "24"))
        self.ch006.setText(_translate("MainWindow", "6"))
        self.ch023.setText(_translate("MainWindow", "23"))
        self.ch017.setText(_translate("MainWindow", "17"))
        self.ch018.setText(_translate("MainWindow", "18"))
        self.ch011.setText(_translate("MainWindow", "11"))
        self.ch005.setText(_translate("MainWindow", "5"))
        self.ch028.setText(_translate("MainWindow", "28"))
        self.ch014.setText(_translate("MainWindow", "14"))
        self.ch027.setText(_translate("MainWindow", "27"))
        self.ch010.setText(_translate("MainWindow", "10"))
        self.ch007.setText(_translate("MainWindow", "7"))
        self.ch013.setText(_translate("MainWindow", "13"))
        self.ch021.setText(_translate("MainWindow", "21"))
        self.ch016.setText(_translate("MainWindow", "16"))
        self.ch008.setText(_translate("MainWindow", "8"))
        self.ch009.setText(_translate("MainWindow", "9"))
        self.ch001.setText(_translate("MainWindow", "1"))
        self.ch012.setText(_translate("MainWindow", "12"))
        self.ch002.setText(_translate("MainWindow", "2"))
        self.ch015.setText(_translate("MainWindow", "15"))
        self.ch004.setText(_translate("MainWindow", "4"))
        self.names.setText(_translate("MainWindow", "Signal Names"))
        #self.save.setText(_translate("MainWindow", "Save"))
        
        #Frequency
        self.enterFreq.setText(_translate("MainWindow","  Enter Frequency"))
        self.hz.setText(_translate("MainWindow","Hz"))
        
        #IP Address
        self.enterIP.setText(_translate("MainWindow", "    Enter IP Address\n  i.e. 192.168.0.100"))
        self.colon1.setText(_translate("MainWindow", "  :"))
        self.colon2.setText(_translate("MainWindow", "  :"))
        self.colon3.setText(_translate("MainWindow", "  :"))
        
        #Database
        self.mea_name.setText(_translate("MainWindow", " Measurement Name"))
        self.bucket.setText(_translate("MainWindow", "  Bucket"))
        self.org.setText(_translate("MainWindow", " Organization"))
        self.token.setText(_translate("MainWindow", " Token"))
        self.enterInflux.setText(_translate("MainWindow", " Enter Influx Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_project()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
